#!/usr/bin/env node
// Regenerates references/CATALOG.md from the card frontmatter.
// Run from the repo root: node scripts/build-catalog.mjs

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const refs = join(root, "references");

const CHAIN_NAMES = {
  1: "Ethereum",
  10: "Optimism",
  56: "BNB Chain",
  130: "Unichain",
  137: "Polygon",
  146: "Sonic",
  999: "HyperEVM",
  5000: "Mantle",
  8453: "Base",
  42161: "Arbitrum",
  43114: "Avalanche",
  59144: "Linea",
  81457: "Blast",
  534352: "Scroll",
  747474: "Katana",
};

const CATEGORY_TITLES = {
  dex: "DEXs & swap aggregators",
  yield: "Yield & vaults",
  credit: "Lending & credit",
  staking: "Staking & liquid (re)staking",
  perp: "Perpetual futures",
  bridge: "Bridges & cross-chain",
  vault: "Managed vaults",
  prediction: "Prediction markets",
  options: "Options",
  other: "Other",
};

// Tolerant frontmatter parser: handles scalars, inline lists [a, b],
// block lists (- item), and multi-line folded scalars (indented continuations).
function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const out = {};
  let key = null;
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (kv) {
      key = kv[1];
      const v = kv[2].trim();
      if (v === "") out[key] = [];
      else if (v.startsWith("[")) {
        out[key] = v
          .replace(/^\[|\]$/g, "")
          .split(",")
          .map((s) => s.trim().replace(/^["']|["']$/g, ""))
          .filter(Boolean);
      } else out[key] = v.replace(/^["']|["']$/g, "");
    } else if (key !== null) {
      const item = line.match(/^\s+-\s+(.*)$/);
      if (item) {
        if (!Array.isArray(out[key])) out[key] = out[key] === undefined || out[key] === "" ? [] : [out[key]];
        out[key].push(item[1].trim().replace(/^["']|["']$/g, ""));
      } else if (/^\s+\S/.test(line) && typeof out[key] === "string") {
        out[key] += " " + line.trim();
      }
    }
  }
  return out;
}

const load = (dir) =>
  readdirSync(join(refs, dir))
    .filter((f) => f.endsWith(".md") && f !== "CATALOG.md")
    .map((f) => ({ file: f, fm: parseFrontmatter(readFileSync(join(refs, dir, f), "utf8")) }))
    .sort((a, b) => a.file.localeCompare(b.file));

const protocols = load("protocols");
const strategies = load("strategies");
const scanner = load("scanner");

const chains = (ids) =>
  (ids ?? []).map((id) => CHAIN_NAMES[id] ?? String(id)).join(", ") || "—";
const list = (v) => (Array.isArray(v) ? v.join(", ") : v ?? "—") || "—";
const link = (dir, file, label) => `[${label}](${dir}/${file})`;

let md = `# Catalog

Generated by \`scripts/build-catalog.mjs\` — do not edit by hand.

- **${protocols.length} protocol cards** across ${new Set(protocols.map((p) => p.fm.category)).size} categories
- **${strategies.length} strategy archetypes**
- **${scanner.length} scanner cards** (the opportunity-scanning method)

## Protocols

`;

const byCategory = new Map();
for (const p of protocols) {
  const c = p.fm.category ?? "other";
  if (!byCategory.has(c)) byCategory.set(c, []);
  byCategory.get(c).push(p);
}

const order = Object.keys(CATEGORY_TITLES).filter((c) => byCategory.has(c));
for (const c of [...byCategory.keys()]) if (!order.includes(c)) order.push(c);

for (const cat of order) {
  md += `### ${CATEGORY_TITLES[cat] ?? cat} (${byCategory.get(cat).length})\n\n`;
  md += `| Protocol | Chains | Actions | Tokens |\n|---|---|---|---|\n`;
  for (const p of byCategory.get(cat)) {
    md += `| ${link("protocols", p.file, p.fm.protocol ?? p.file.replace(".md", ""))} | ${chains(p.fm.chains)} | ${list(p.fm.actions)} | ${list(p.fm.tokens)} |\n`;
  }
  md += "\n";
}

md += `## Strategy archetypes

| Strategy | Capabilities | When it applies |\n|---|---|---|\n`;
for (const s of strategies) {
  const trig = String(s.fm.triggers ?? "").replace(/\|/g, "\\|");
  md += `| ${link("strategies", s.file, s.fm.archetype ?? s.file.replace(".md", ""))} | ${list(s.fm.capability)} | ${trig} |\n`;
}

md += `\n## Scanner

| Module | Instrument |\n|---|---|\n`;
for (const s of scanner) {
  md += `| ${link("scanner", s.file, s.fm.module ?? s.file.replace(".md", ""))} | ${s.fm.instrument ?? "—"} |\n`;
}

writeFileSync(join(refs, "CATALOG.md"), md);
console.log(`Wrote references/CATALOG.md (${protocols.length} protocols, ${strategies.length} strategies, ${scanner.length} scanner cards)`);
