#!/usr/bin/env node
// Regenerates references/CATALOG.md from card frontmatter.
// Run from the repo root: node scripts/build-catalog.mjs

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, dirname, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const refs = join(root, "references");

// Tolerant frontmatter parser: scalars, inline lists [a, b], block lists (- item),
// and folded scalars (>- with indented continuations).
function parseFrontmatter(text) {
  const m = text.match(/^---\n([\s\S]*?)\n---/);
  if (!m) return {};
  const out = {};
  let key = null;
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (kv) {
      key = kv[1];
      const v = kv[2].trim();
      if (v === "" || v === ">-" || v === ">" || v === "|") out[key] = v === "" ? [] : "";
      else if (v.startsWith("[")) {
        out[key] = v.replace(/^\[|\]$/g, "").split(",")
          .map((s) => s.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
      } else out[key] = v.replace(/^["']|["']$/g, "");
    } else if (key !== null) {
      const item = line.match(/^\s+-\s+(.*)$/);
      if (item) {
        if (!Array.isArray(out[key])) out[key] = out[key] ? [out[key]] : [];
        out[key].push(item[1].trim().replace(/^["']|["']$/g, ""));
      } else if (/^\s+\S/.test(line)) {
        if (typeof out[key] === "string") out[key] = (out[key] ? out[key] + " " : "") + line.trim();
      }
    }
  }
  return out;
}

function walk(dir, acc = []) {
  for (const name of readdirSync(dir).sort()) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, acc);
    else if (name.endsWith(".md") && name !== "CATALOG.md" && name !== "card-format.md") acc.push(p);
  }
  return acc;
}

const cards = walk(refs).map((p) => {
  const rel = relative(refs, p).split(sep).join("/");
  return { path: rel, fm: parseFrontmatter(readFileSync(p, "utf8")) };
});

const clean = (v) => {
  const s = Array.isArray(v) ? v.join(", ") : (v ?? "");
  return String(s).replace(/\s+/g, " ").replace(/\|/g, "\\|").trim();
};
const title = (c) => c.fm.title || c.path.replace(/\.md$/, "");
const trig = (c) => {
  const t = clean(c.fm.triggers);
  return t.length > 160 ? t.slice(0, 157) + "…" : t || "—";
};

const SECTIONS = [
  { key: "perpetuals", heading: "Perpetual futures", dir: "perpetuals/" },
  { key: "prediction-markets", heading: "Prediction markets", dir: "prediction-markets/" },
  { key: "quant", heading: "Quant", dir: "quant/" },
];

const GROUPS = {
  data: "Data",
  indicators: "Indicators",
  strategies: "Strategies",
  execution: "Execution",
  risk: "Risk",
  validation: "Validation",
};

let md = `# Catalog

Generated by \`scripts/build-catalog.mjs\` — do not edit by hand.

${cards.length} cards across ${SECTIONS.length} sections.

`;

for (const s of SECTIONS) {
  const inSection = cards.filter((c) => c.path.startsWith(s.dir));
  if (!inSection.length) continue;
  md += `## ${s.heading}\n\n`;

  const ungrouped = inSection.filter((c) => !c.fm.group);
  if (ungrouped.length) {
    md += `| Card | Covers |\n|---|---|\n`;
    for (const c of ungrouped) md += `| [${title(c)}](${c.path}) | ${trig(c)} |\n`;
    md += "\n";
  }

  const groups = [...new Set(inSection.map((c) => c.fm.group).filter(Boolean))]
    .sort((a, b) => Object.keys(GROUPS).indexOf(a) - Object.keys(GROUPS).indexOf(b));
  for (const g of groups) {
    md += `### ${GROUPS[g] ?? g}\n\n| Card | Covers |\n|---|---|\n`;
    for (const c of inSection.filter((c) => c.fm.group === g))
      md += `| [${title(c)}](${c.path}) | ${trig(c)} |\n`;
    md += "\n";
  }
}

writeFileSync(join(refs, "CATALOG.md"), md);
console.log(`Wrote references/CATALOG.md (${cards.length} cards)`);
